---
name: Expo CI
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: bycedric/expo-github-action-concept@master
        with:
          expo-username: bycedric
          expo-password: ${{ secrets.password }}
      - run: npm ci
      - run: expo doctor
      - run: expo diagnostics
      - run: expo publish
