---
name: Expo CI
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [10, 12]
        packager: [npm, yarn]
        expo: [3.10.x, 3.11.x]
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: expo/expo-github-action@refactor/use-ncc
        with:
          expo-version: ${{ matrix.expo }}
          expo-username: bycedric
          expo-password: ${{ secrets.password }}
          expo-packager: ${{ matrix.packager }}
      - run: npm ci
      - run: expo doctor
      - run: expo diagnostics
